modbus:
  name: edp_box_1
  type: serial
  method: rtu
  port: /dev/ttyUSB0
  baudrate: 9600
  stopbits: 1
  bytesize: 8
  parity: N
  timeout: 10

sensor:
  - platform: modbus
    scan_interval: 5
    registers:
      - name: 'Frequency'
        hub: edp_box_1
        slave: 1
        register: 127
        register_type: input
        unit_of_measurement: 'Hz'
        count: 1
        scale: 0.1
        offset: 0
        precision: 2
        # long unsigned
        data_type: uint
        
      - name: 'Voltage L1'
        hub: edp_box_1
        slave: 1
        register: 108
        register_type: input
        unit_of_measurement: 'V'
        count: 1
        scale: 0.1
        offset: 0
        precision: 1
        # long unsigned
        data_type: uint

      - name: 'Current L1'
        hub: edp_box_1
        slave: 1
        register: 109
        register_type: input
        unit_of_measurement: 'A'
        count: 1
        scale: 0.1
        offset: 0
        precision: 1
        # long unsigned
        data_type: uint
        
      - name: 'Power factor'
        hub: edp_box_1
        slave: 1
        register: 123
        register_type: input
        unit_of_measurement: 'p.u.'
        count: 1
        scale: 0.001
        offset: 0
        precision: 3
        # long unsigned
        data_type: uint

  - platform: modbus
    scan_interval: 10
    registers:
      - name: 'Tariff'
        ## 1 para Vazio - 2 para Ponta - 3 para Cheia
        hub: edp_box_1
        slave: 1
        register: 11
        register_type: input
        count: 1
        data_type: custom
        structure: ">Bx"
                
      - name: 'Switch Control State'
        ## 0 para disconectado - 1 para conectado - 2 para preparado a reconectar
        hub: edp_box_1
        slave: 1
        register: 132
        register_type: input
        count: 1
        data_type: custom
        structure: ">Bx"
